### ISSUE TITLE
Issues or more documentation needed ?

### ISSUE THREAD

**Issue by kissu** [blokwise/dynamic#1]
Thanks for the package ! Was looking for something like that few weeks ago. ❤️ 

I do have a feedback on some stuff that is broken.
I do have a full static target and launching my `yarn dev`, it gives me the correct path for each components properly ! 💪🏻 
![image](https://user-images.githubusercontent.com/5133074/99743712-894fac00-2ad6-11eb-9b13-e772d50f3f6d.png)

#### PS: I was wondering if that kind of output could be silenced in some future btw (like a boolean in the module config). ^^

My `.vue` file does have
```html
<nav
  v-for="link in sidebarLinksData"
>
  <div>
    <nuxt-dynamic :name="link.linkIcon" class="inline w-5 h-5"></nuxt-dynamic> <!-- I've tried w/ the lazy variant too ! -->
    <!-- more code... -->
  </div>
</nav>
```

I'm basically looping on an array in a `v-for` loop and using an object to insert dynamic SVGs thanks to [nuxt-svg-loader](https://github.com/Developmint/nuxt-svg-loader).

```js
sidebarLinksData() {
  return [
    {
      linkIcon: 'svg-grey-home',
    },
    {
      linkIcon: 'svg-grey-home',
    },
    {
      linkIcon: 'svg-grey-home',
    },
    {
      linkIcon: 'svg-grey-baby',
    },
    {
      linkIcon: 'svg-grey-game',
    },
    {
      linkIcon: 'svg-grey-game',
    },
    {
      linkIcon: 'svg-grey-game',
    },
  ]
},
```

I do then have that kind of error.
![image](https://user-images.githubusercontent.com/5133074/99744520-23642400-2ad8-11eb-85d0-e6a38191b47d.png)
And here is the visual, icons are missing
![image](https://user-images.githubusercontent.com/5133074/99747679-50fe9c80-2adb-11eb-8f20-f9167eeb4319.png)

So here, it seems like it's not happy w/ how it's named. Moving from `svg-grey-home` to `svgGreyHome` helps removing that error. 
I was just wondering why you told in your [blog post](https://julianderungs.medium.com/crank-up-auto-import-for-dynamic-nuxt-js-components-54e7f198fc16) that:
> It prepares an array of components with their component names (PascalCase and kebab-case) and their relative filepaths.

I do misunderstood here ? 🤔 

Still, once changed it looks pretty nice !
![image](https://user-images.githubusercontent.com/5133074/99747300-8ce53200-2ada-11eb-9ea6-0171e6adb349.png)
But ! When I do refresh the page **once**, then I do have that error
![image](https://user-images.githubusercontent.com/5133074/99747499-ebaaab80-2ada-11eb-87a9-682747326a38.png)
In the console
![image](https://user-images.githubusercontent.com/5133074/99743839-c9169380-2ad6-11eb-90aa-7cd78eaf7482.png)

If I `rm -rf dist .nuxt` and try to `yarn dev` back again, it stays stuck at the same error.

Meanwhile, I found out that if I use the PascalCase syntax back in my object and update the section of code w/
```html
<client-only>
  <nuxt-dynamic :name="link.linkIcon" class="inline w-5 h-5"></nuxt-dynamic>
</client-only>
```
then it works great.

So yeah, I need to dive a bit more into the blog post that Markus linked me about [failed hydration](https://blog.lichter.io/posts/vue-hydration-error/#how-to-recognize-failing-hydration) but thought that my input may be useful to fix some of these issues/add some options. ^^

**Comment by aerophobic** [comment]
Hi @kissu thanks for submitting your issue.

Regarding your questions:

### kebab-case component names
kebab-case component names are not supported as of now. The information about auto-importable components from `@nuxt/components` is populated with all the kebab-cases component names - the module actually does not make use of it by now. This feature is missing and I will add this in the next release.

### Failed hydration
Can you have a look into your yarn.lock (or package-lock.json) and tell me which version of `vue-lazy-hydration` is installed in your project?

### Silence the console output
The console output should only state the used prefixes. The way the module detects all those prefixes is based on PascalCase aswell. Thats why in your case, component names instead of prefixes are found. I guess you use kebab-cased filenames aswell, can you confirm that? I'm going to fix this aswell with the next release.

**Comment by kissu** [comment]
Thanks for the quick reply ! 👋🏻 

Alright, thanks for the component names ! 💯 

Ok, I do already had `vue-lazy-hydration` installed before trying this package so...I do have `"vue-lazy-hydration": "^2.0.0-beta.1",` installed by myself and `vue-lazy-hydration@1.0.0-beta.14:` installed through `@blokwise/dynamic`.
I guess that this one may not help too ? 😓 

My configuration for the components is as follows, an array mapping each of my SVG directories, in that format
```js
{
  path: '~/assets/svg/grey',
  prefix: 'svg-grey',
  extensions: ['svg'],
},
```
and with that kind of naming
![image](https://user-images.githubusercontent.com/5133074/99809545-b8036c00-2b42-11eb-9a69-1d9ab22f5793.png)

and working in my template with a simple
```html
<svg-grey-baby-bottle></svg-grey-baby-bottle>
```

Yeah, I do like to use snake_case for the assets. 😆 
Hope my feedback helps !

**Comment by aerophobic** [comment]
Thanks for your reply.

### Component names
Snake case - thats an interesting choice ;) So I will fix the issue for the prefixes to cover all those fancy options.

### Hydration
The __esModule error you stated initially (aswell the one which mentions `HydrateSsrOnly`) are related to `vue-lazy-hydration` v.2 (more information can be found here: [breaking changes](https://github.com/maoberlehner/vue-lazy-hydration#upgrade-v1x-to-v2x)). HydrateSsrOnly is now called HydrateNever beginning with v.2
I'll update the module to use `vue-lazy-hydration` > v.2 as soon as its ready (there were some issues while hydrating).
Until then: remove the newer package and it should work as expected.

**Comment by kissu** [comment]
Haha, sorry could have found it by myself but I did not checked `vue-lazy-hydration` enough. 😅 
It's working great. I'll wait until this package get's updated before using `vue-lazy-hydration` again ! And yeah, since both are in beta, I'll use it w/ caution.

Thanks for the debugging and your work ! 🙏🏻

**Comment by aerophobic** [comment]
Perfect! 💯 
I will solve the kebab-case component namings to further enhance this module for use-cases like yours. Related issue is #2.

**Comment by kissu** [comment]
Thanks for helping devs all around the world writing (even) less code. 😋

**Comment by aerophobic** [comment]
I'll always strive for less work on daily tasks 😉

kebab-cased components can now be auto imported - **starting with v.1.0.4**
