### ISSUE TITLE
Uncaught (in promise) TypeError: can't access property "__esModule", comp is undefined

### ISSUE THREAD

**Issue by asencis** [blokwise/dynamic#10]
I'm not sure what to add here, other than a previously working Component can't be used with the NuxtDynamic component:

<img width="307" alt="Screenshot 2021-03-02 at 10 08 10" src="https://user-images.githubusercontent.com/70026705/109632718-407caa00-7b3f-11eb-9901-f29314069835.png">

I've got watchers, computed, and methods ... and data is an arrow function... not sure what else would be needed?

**Comment by aerophobic** [comment]
Hi @asencis 

Thanks for submitting this issue. I looked into it and it seems that in some cases the vue-lazy-hydration upgrade I pushed 3 days ago does not work as expected. I'll probably revert the upgrade to provide a fully working solution with this package.

Please consider to work with @blokwise/dynamic@1.1.0 until a fix is published.

**Comment by aerophobic** [comment]
Latest version of @blokwise/dynamic ([v1.3.0](https://github.com/blokwise/dynamic/releases/tag/v1.3.0)) fixes this behaviour.
