### ISSUE TITLE
Question: passing data and inheritAttrs?

### ISSUE THREAD

**Issue by memic84** [blokwise/dynamic#3]
Hi there,

This is my situation:

```      
<NuxtDynamic
	v-for="(component, index) in page.paragraphs"
	:key="index"
	:name="component.__typename"
	:data="component"
/>
```

When i pass data with props, the prop is binded in the HTML:
![image](https://user-images.githubusercontent.com/3043840/105824843-2dfed600-5fbf-11eb-9885-cb558b8267b3.png)

Or when passing the component data through with v-bind:
```
      <NuxtDynamic
        v-for="(component, index) in page.paragraphs"
        :key="index"
        :name="component.__typename"
        v-bind="component"
      />
```

![image](https://user-images.githubusercontent.com/3043840/105825126-88983200-5fbf-11eb-85db-8f58c93f4dfd.png)

Is it possible to omit or disable the inheritAttrs? Then working with large HTML, the output goes also in an attribute.

Or should i be using scoped slots?

**Comment by aerophobic** [comment]
Hi @memic84

Good point! Didn't think about disabling the inheritance yet. But this would be the right way to do it. As far as I see that would solve your issue, make the DOM less polluted and nevertheless still work as expected.
I could set `inheritAttrs: false` inside the `Dynamic` component. Do you see any need to have the inheritance activateable through a prop?

WDYT?

**Comment by memic84** [comment]
I have tested this, and i agree that added inheritAttrs without a prop to set it would be the best way to handle this. There is no need in the Dynamic component, to have a prop as setting the inheritAttrs won't do anything until you also set inheritAttrs for the component that you are loading.

**Root component**
```
    <NuxtDynamic
      v-for="(component, index) in page.paragraphs"
      :key="index"
      :name="component.__typename"
      v-bind="component"
    />
```

**Dynamic component**
```
  <component
    v-if="lazyComponent"
    :is="lazyComponent"
    v-bind="$attrs"
    class="blokwise__dynamic"
    v-on="$listeners"
  >
```
...
```
export default {
  name: "Dynamic",

  inheritAttrs: false,
```


**Simple component to render text from a headless cms**
```
<template>
  <div v-html="$attrs.text"></div>
</template>

<script>
export default {
  name: 'ParagraphText',
  inheritAttrs: false,
}
</script>
```

I also added a PR, if that's OK.

**Comment by aerophobic** [comment]
Awesome! Thanks for your contribution. Let's merge that into the `master` branch. You need to change your pull request, because you targeted the `master` branch of your own repository 😉.
Can you follow the commitlint standards for the message and prepend a common type ([commitlint types](https://github.com/conventional-changelog/commitlint#what-is-commitlint))? Would be great, thanks 🙏

**Comment by memic84** [comment]
Thanks! My mistake, i just changed the pull request and the right commit message. Let me know if that's ok.

**Comment by aerophobic** [comment]
@memic84 Thanks for your contribution 🙏 I'll publish a new version of the package including #5 and #6 asap
