### ISSUE TITLE
Remove class blokwise__dynamic

### ISSUE THREAD

**Issue by memic84** [blokwise/dynamic#4]
Is it possible to remove the class 'blokwise__dynamic' as we can set this also on the parent component.

```
  <component
    v-if="lazyComponent"
    :is="lazyComponent"
    v-bind="$attrs"
    class="blokwise__dynamic"
    v-on="$listeners"
  >
```

**Comment by aerophobic** [comment]
You're right - we can remove this class and handle it from outside.

**Comment by aerophobic** [comment]
@memic84 Thanks for your contribution 🙏 I'll publish a new version of the package including #5 and #6 asap
