### ISSUE TITLE
 Unknown custom element: <NuxtDynamic> - did you register the component correctly?

### ISSUE THREAD

**Issue by kayw-geek** [blokwise/dynamic#7]
My code :
`<NuxtDynamic  name="miniDetail"/>`

My nuxt.config.js:
`  modules: [
    '@nuxtjs/axios',
    'nuxt-sass-resources-loader',
    ['@nuxtjs/pwa', {
      icon: false
    }],
    'nuxt-clipboard2',
    '@blokwise/dynamic'
  ],`
Where is my problem? I have executed npm install @blokwise/dynamic?

**Comment by aerophobic** [comment]
Hi @kayw-geek 
Seems to be configured correctly. Did you enable `@nuxt/components`? Which version of nuxt are you using?

**Comment by kayw-geek** [comment]
Hello, my nuxt version is 2.3.4, I also manually installed @nuxt/components ^1.2.5

**Comment by aerophobic** [comment]
Alright - did you enable it in nuxt.config.js?
```
export default {
  components: true
}
```

**Comment by kayw-geek** [comment]
yes .This is my nuxt.config.js content.
`export default {
  components: true,
  fetchOnServer: true,
`

**Comment by kayw-geek** [comment]
I checked my local .nuxt/components directory and did not see NuxtDynamic related files. Is this normal? The @blokwise\dynamic module is seen in .node_modules;

**Comment by aerophobic** [comment]
The [usage section](https://github.com/nuxt/components#usage) of `@nuxt/components` says:
"Note: If using nuxt `2.10...2.13`, you have to also manually install and add `@nuxt/components` to buildModules inside nuxt.config."

It looks like you need at least version `2.10` of nuxt to enable `@nuxt/components` in your application. It definitely should have components registered inside `.nuxt/components/index.js`, e.g.:

```
export { default as Example } from '../..\\node_modules\\@anypackage\\components\\Example.vue'

export const LazyExample = import('../..\\node_modules\\@anypackage\\components\\Example.vue' /* webpackChunkName: "components/example" */).then(c => c.default || c)
```

If you have any local component in your project, there should be definitely some imports inside the file. Can you check that?

**Comment by kayw-geek** [comment]
Ok thank you i try to upgrade my nuxt
