### ISSUE TITLE
Upgrade vue-lazy-hydration to latest (2.0.0-beta.4)

### ISSUE THREAD

**Issue by memic84** [blokwise/dynamic#8]
Hi there,

Can we upgrade the **vue-lazy-hydration** package to v2? I see that the version 1 is also a beta version, and on NPM there is a **version 2.0.0-beta.4** released, a couple of months ago.

**Breaking changes**
https://github.com/maoberlehner/vue-lazy-hydration#upgrade-v1x-to-v2x

Seems like some minor changes.

**Comment by aerophobic** [comment]
Hi @memic84 

Thanks for the input. I know, that the package is lagging behind. When I first released NuxtDynamic on 2020-11-18 there have been issues with the version 2.0.0 of vue-lazy-hydration (related to rendering and event listeners). But as I can see there have been made several fixes the following days (2020-11-19 - 2020-11-21).

So I guess the chances are good the issues are gone with the latest version - Therefore no need to stay with 1.0.0.

As you already discovered, there are just minor changes to implement 2.0.0, not much to change. If you'd like to you can make a pull request and I'll verify that everything works as expected. If you don't have the resources to do so, I'll gonna do it myself in the coming days.

**Comment by memic84** [comment]
Hi @aerophobic 

I can make the pull request, but there's some confusion on my side now with the vue lazy hydration package. On NPM it shows the version 2, and the releases on github from vue lazy hydration don't show any version 2.

Not sure what has been fixed, and what now cause i haven't seen any change notes.

**Comment by aerophobic** [comment]
I'll test the new version and bump it if all tests succeed

**Comment by memic84** [comment]
Thanks! Sorry, have been very busy two weeks..

**Comment by aerophobic** [comment]
no worries, same here. I upgraded `vue-lazy-hydration` to the latest version and published a new version of the package (`1.2.0`). I'll close this issue for now - feel free to reopen if you'll experience unexpected behaviour.
