### ISSUE TITLE
Dynamics components in full-static mode

### ISSUE THREAD

**Issue by italo1983** [blokwise/dynamic#9]
Hi, i've used your library to render dynamics components picked up from Strapi API.
Components are renderized well but when exporting to static target (full-static mode with ssr) child components that are using NuxtDynamic are not renderized as flattened HTML.

For example:

```html
 <template>
   <div class="w-full" :class="[data.css]">
    <Header class="w-full"  :menu="menu" :subMenu="subMenu" :lang="route[0]"/>
     <div class="padding-uppo-body">
       <NuxtDynamic v-for="(component, itemObjKey) in components" :name="component.component" :data="component.data" :key="itemObjKey" :lang="route[0]" :father="father" :resized="resized" v-model="resized" />
       <Footer :footerMenuRisorse="footerMenuRisorse" :footerMenuUppo="footerMenuUppo" :footerMenuProdotti="footerMenuProdotti" :lang="route[0]"/>
     </div>
   </div>
 </template>
```
Generated HTML contain Footer but not other components imported with NuxtDynamic, this last one is injected client side when opening the page.

For example:
```htm
 <div class="padding-uppo-body" data-v-45daa1a3> 
 <!-- Missing some components imported via NuxtDynamic -->
 <footer class="bg-footer-uppo text-white text-left" data-v-5062cb1e data-v-45daa1a3>
 .....
 </div>
```
How to achieve a full-static HTML with this library? I'm missing something?
Thanks

**Comment by italo1983** [comment]
Solved using fetch instead of mounted.

**Comment by aerophobic** [comment]
@italo1983 sorry for the late answer. Was guessing the same - you should fetch all data in fetch or asyncdata and you are ready to go. the components will definitely be rendered in full static mode when the data provided by cms is already fetched.

glad to hear you are using the package and it works like you want it to 🙂
